### ISSUE TITLE
[Adblock BUG] Extension is no longer working.

### ISSUE THREAD

**Issue by loekyn** [CharlieS1103/spicetify-extensions#92]
## Update, it is working now!
If re-installing the adblocker is not working for you, try replacing the script with the new merged adblock script manually, and adding the ''adblock.js'' under the `[AdditionalOptions]'s extensions` in config file `config-xpui`.
```
[AdditionalOptions]
...
extensions            = adblock.js
```

## Describe bug
Advertisements, such as banners and ad-songs, are still playing after every song.

## Steps to replicate
It will show up after a few songs.

## Necessary screenshots
![edited  Screenshot 2023-09-28 112235](https://github.com/CharlieS1103/spicetify-extensions/assets/65395705/f5b7021a-7b03-4340-b443-aa83a4aba6af)

## Spicetify and Spotify Version

> Spotify for Windows (64 bit)
> 1.2.21.1104.g42cf0a50
> Spicetify v2.24.2
> Theme: marketplace
> Extensions: adblock.js
> Custom apps: marketplace

## Config file:
```
[Setting]
inject_css              = 1
overwrite_assets        = 0
prefs_path              = C:\Users\X\AppData\Roaming\Spotify\prefs
color_scheme            = 
inject_theme_js         = 1
replace_colors          = 1
spotify_launch_flags    = 
check_spicetify_upgrade = 0
spotify_path            = C:\Users\X\AppData\Roaming\Spotify
current_theme           = marketplace

[Preprocesses]
disable_upgrade_check = 1
disable_sentry        = 1
disable_ui_logging    = 1
remove_rtl_rule       = 1
expose_apis           = 1

[AdditionalOptions]
sidebar_config        = 1
home_config           = 1
experimental_features = 1
extensions            = 
custom_apps           = marketplace

[Patch]

; DO NOT CHANGE!
[Backup]
version = 1.2.21.1104.g42cf0a50
with    = 2.24.2
```

**Comment by loekyn** [comment]
## Additional screenshoot
![Screenshot 2023-09-29 111955](https://github.com/CharlieS1103/spicetify-extensions/assets/65395705/a64fd0be-dadf-4d48-8ddc-44b11c626fcf)

## I'm not sure will this log from the console will help or not, but here it is
```
raw.githubusercontent.com/spicetify/spicetify-marketplace/main/manifest.json:1     Failed to load resource: the server responded with a status of 404 ()
xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/leaderboard
extension.js:1 Initializing Spicetify Marketplace v0.8.7
extension.js:1 Loaded Marketplace extension
about:srcdoc:1 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
adblock.js?time=1695960314478:53 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'putOverridesValues')
    at delayAds (adblock.js?time=1695960314478:53:55)
    at adblock (adblock.js?time=1695960314478:26:5)
    at adblock.js?time=1695960314478:79:3
gew4-spclient.spotify.com/remote-config-resolver/v3/configuration:1     Failed to load resource: the server responded with a status of 404 ()
vendor~xpui.js:29 provider:transport resolve error T Object
f @ vendor~xpui.js:29
index.html:1 Uncaught (in promise) T
VM27 pubads_impl.js:10 The following functions are deprecated: googletag.pubads().setTagForChildDirectedTreatment(), googletag.pubads().clearTagForChildDirectedTreatment(), googletag.pubads().setRequestNonPersonalizedAds(), and googletag.pubads().setTagForUnderAgeOfConsent(). Please use googletag.pubads().setPrivacySettings() instead.
Cy @ VM27 pubads_impl.js:10
VM51 show_ads.js:28 You are using deprecated show_ads.js script to display AdSense ads. To improve performance of your ads switch to the modern adsbygoogle.js script. See instructions on https://support.google.com/adsense/answer/9190028.
Ob @ VM51 show_ads.js:28
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/8461.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-routes-collection-songs.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/2355.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/7857.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
vendor~xpui.js:29 NotFoundError: GET request to sp://core-playlist/v1/playlist/spotify%3Aplaylist%3A37i9dQZF1EYkqdzj48dyYq/?responseFormat=protobufJson&start=0&length=0 failed with status code 404
    at l.onSuccess (xpui.js:1:2162782)
    at onSuccess (xpui.js:1:2162596)
onError @ vendor~xpui.js:29
h @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
Promise.catch (async)
c @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
extension.js:1     GET https://raw.githubusercontent.com/3raxton/spicetify-custom-apps-and-extensions/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/TheRandomLabs/Scoop-Spotify/master/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
vendor~xpui.js:29 NotFoundError: GET request to sp://core-playlist/v1/playlist/spotify%3Aplaylist%3A37i9dQZF1EYkqdzj48dyYq/?responseFormat=protobufJson&start=0&length=0 failed with status code 404
    at l.onSuccess (xpui.js:1:2162782)
    at onSuccess (xpui.js:1:2162596)
onError @ vendor~xpui.js:29
h @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
Promise.catch (async)
c @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
Promise.then (async)
(anonymous) @ vendor~xpui.js:29
```

**Comment by Cirpno** [comment]
thanks for showing this solution, works like a charm
